SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE DeleteEvent
	@UserID_FK int,
	@EventID int
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM Event_Table WHERE Event_Table.EventID = @EventID AND Event_Table.UserID_FK = @UserID_FK
END
GO